/**
 * Backend Configuration
 * Auto-generated by fix-backend-routes.js
 */

module.exports = {
  // Database configuration
  database: {
    name: 'betpro',
    collections: {
      users: 'Users',
      transactions: 'Transactions',
      bets: 'Bets',
      events: 'Events',
      markets: 'Markets',
      settings: 'Settings'
    }
  },
  
  // API configuration
  api: {
    port: 5000,
    jwtSecret: 'betpro-secret-key-2025',
    jwtExpiration: '24h'
  }
};
